version: '3.1'

services:

  gameap:
    image: gameap/gameap
    restart: always
    volumes:
        - ./gameap-certs:/var/www/gameap/storage/app/certs
    environment:
        ADMIN_PASSWORD: fVsT3GFW%2s!dv
        APP_LANG: ru
        APP_URL: https://example.com
        DB_CONNECTION: mysql
        DB_HOST: db
        DB_DATABASE: gameap
        DB_USERNAME: gameap
        DB_PASSWORD: gameap
    depends_on:
          - db
  db:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: rootpass
        MYSQL_DATABASE: gameap
        MYSQL_USER: gameap
        MYSQL_PASSWORD: gameap
